sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build source branch only
git:
  depth: 1
install:
  - npm install
before_script:
  - git config --global user.name '{GitUserName}'   
  - git config --global user.email '{GitUserEMail}'  
  - sed -i "s/__GitOAuthToken__/${GITHUB_TOKEN}/" _config.yml
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
